<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta content="text/html; charset=ISO-8859-1"
 http-equiv="content-type">
  <title>Batch Wafer IV Submission</title>
</head>
<body>

<form action='batchwafersubmit.php' method='post' enctype='multipart/form-data'>
<?php
include('../functions/submitfunctions.php');
include('../functions/popfunctions.php');
include('../functions/curfunctions.php');
?>


<br>
This form is for populating wafer IV scans in batch using the document generated by RTI.
<br>
UNDER TEST 
<br>
.xml file:
<input name="txt" type="file">
<br>
<br>
User:
<textarea cols="10" rows="1" name="user"></textarea>
<br>
<br>
Location:
<textarea cols="10" rows="1" name="loc"></textarea>
<br>
<br>

<?php
conditionalSubmit(0);
echo "<br>";


if(isset($_POST['submit']) &&  $_FILES['txt']['size'] > 0 && $_POST['user'] != "" && $_POST['loc'] != ""){

	batchwafer($_FILES['txt']['tmp_name'],$_FILES['txt']['name'],$_FILES['txt']['size'],$_POST['user'], $_POST['loc']);

}
?>
</form>

<br>

<form method="link" action="../index.php">
<input type="submit" value="MAIN MENU">
</form>

</body>
</html>
